### ISSUE TITLE
鉱石を置いたりパーミッションにブロックを置いたりをすると置いた分だけアイテムが減って最終的にはなくなる

### ISSUE THREAD

**Issue by fuyutsuki** [ElementX-Network/issue-tracker#34]
> Reported by: ひますぎてひまわり#9127

## 再現手順

鉱石を置いたりパーミッションにブロック置いたりするとなる

## 補足

鉱石を置いたりパーミッションにブロックを置いたりしてブロックがなくなったらそのブロックが置いてあったスロットになんでもいいのでアイテムを置くと戻ってくる

**Comment by DaisukeDaisuke** [comment]
下記のコミットにておそらく修正済み
https://bit.ly/3WfPZPQ

**Comment by DaisukeDaisuke** [comment]
修正を確認済み
