### ISSUE TITLE
通知ロール作ってほしい

### ISSUE THREAD

**Issue by fuyutsuki** [ElementX-Network/issue-tracker#36]
> Requested by: ねむぬーぶ#8836

## なぜこれが必要なのか

一度にアプデしたり等everyoneやhereを連発することがある為、メンション専用のロールを作ったほうがdiscordの参加ハードルが低くなると思う。discord側にあるサーバーミュートは神機能なので視覚的通知は来るクソ。あとこんなフォームあったんですね

**Comment by DaisukeDaisuke** [comment]
> 視覚的通知は来る

![Desktop Screenshot 2022 12 24 - 20 32 08 39](https://user-images.githubusercontent.com/17798680/209434112-7ffb6bc0-b767-4b65-87b0-b1bdd15fbbc6.png)

**Comment by fuyutsuki** [comment]
作成しました。
