### ISSUE TITLE
感圧版などが浮く

### ISSUE THREAD

**Issue by fuyutsuki** [ElementX-Network/issue-tracker#44]
> Reported by: さぼ#8999

## 再現手順

ブロックの上に感圧版を設置して、下のブロックを壊すと感圧版が浮きます。

## 補足

ほぼ回避不可能なスワッパートラップが作られてしまっており、不快感を感じることがかなり多いです。

**Comment by DaisukeDaisuke** [comment]
pmmp 4.12.9にて修正済み
https://discord.com/channels/373199722573201408/546255162222706696/1063176902724030536

**Comment by DaisukeDaisuke** [comment]
修正を確認済み

**Comment by fuyutsuki** [comment]
ありがとうございます！
