### ISSUE TITLE
自身の動作がサーバーに反映されない

### ISSUE THREAD

**Issue by fuyutsuki** [ElementX-Network/issue-tracker#62]
> Reported by: BPくん#6650

## 再現手順

サーバーに参加する

## 補足

チャットも送信できないし自分の姿が三人称視点などから見ても消えている

**Comment by DaisukeDaisuke** [comment]
再起動の直前に参加することにより、発生する場合あり(憶測、1.19.50)
(再起動5秒以下の場合、接続を拒否...?)

**Comment by fuyutsuki** [comment]
#56, #57, #60, #61, #63 と重複
現在調査中です

**Comment by fuyutsuki** [comment]
バージョン起因のバグだったので解決とします
