### ISSUE TITLE
人の頭から降りるとサーバーから蹴られる

### ISSUE THREAD

**Issue by fuyutsuki** [ElementX-Network/issue-tracker#65]
> Reported by: Peppu#1987

## 再現手順

ロビーでCowboyを使い誰かの上に乗ってから降りる

## 補足

https://github.com/ElementX-Network/issue-tracker/issues/64
これと似てるのかなーと思いました
https://youtu.be/hL6AsV1El1I
動画も撮りました

**Comment by DaisukeDaisuke** [comment]
pmmp 4.14.1にて修正済み
> Fixed players getting kicked when linking with entities.

**Comment by fuyutsuki** [comment]
pmmp 4.14.1で修正を適用しました。
