### ISSUE TITLE
アイテムの説明が見れない

### ISSUE THREAD

**Issue by fuyutsuki** [ElementX-Network/issue-tracker#71]
> Reported by: (j゙゚ω゚゙j)#4728

## 再現手順

...→ANNIでFarmerを選ぶ→feastの説明を見る

**Comment by DaisukeDaisuke** [comment]
feastの説明文である`game.annihilation.job.farmer.skill.item.feast.description` (文字認識より)に関して正しく翻訳されていません。
(英語、日本語にて確認)
![Desktop Screenshot 2023 04 08 - 16 17 53 351](https://user-images.githubusercontent.com/17798680/230709114-dd6dd8ef-4433-40b5-9db9-a9acb8fb9a2c.jpg)

**Comment by fuyutsuki** [comment]
https://github.com/ElementX-Network/ElementX-Core/pull/520 で修正
