### ISSUE TITLE
バグnpcから他ゲームを観戦できる

### ISSUE THREAD

**Issue by fuyutsuki** [ElementX-Network/issue-tracker#78]
> Reported by: DaisukeDaisukeSub#0120

## 再現手順

バグnpcの再現手順: 不明

## 補足

バグnpcの特徴: ネームタグチームカラー、lobbyのネームタグ
観戦モードでバグnpc(ネームが灰色以外)をクリックすると、anniに参加しつつ他プレーヤー/ゲーム(スーパージャンプ、ロビー)を観戦できます。
このバグによりクラッシュは発生しないため、放置でも問題ないと思います

**Comment by DaisukeDaisuke** [comment]
![Image](https://user-images.githubusercontent.com/17798680/236130856-d7048320-6240-4ce9-bb62-5fe69a9b778b.jpg)
![Desktop Screenshot 2023 05 04 - 14 57 18 65](https://user-images.githubusercontent.com/17798680/236126119-20af0257-99a3-4f36-baf9-de1d59facfd8.jpg)

**Comment by fuyutsuki** [comment]
現在は発生していなさそうなのでclose
