### ISSUE TITLE
mapを削除する際プレイヤーの意見を聞かないで消すのをやめてほしい。

### ISSUE THREAD

**Issue by fuyutsuki** [ElementX-Network/issue-tracker#92]
> Requested by: よあけ#7181

## なぜこれが必要なのか

anniのプレイヤーが好きなのに運営が嫌いなmapを消すのが多すぎる例ぷりん、ウッドガーデン、たにおん、ハムスタル

**Comment by ryium** [comment]
プレイヤーの意見をすべて取り入れる訳には行きませんが、アンケートは行っていく予定ですのでご了承頂けると幸いです。

**Comment by fuyutsuki** [comment]
プレイヤーが好きだから、運営が嫌いだから、という理由でマップを削除しているわけではなく、ゲームバランスを考慮して削除しています。ご了承下さい。
